### ISSUE TITLE
Load SfM_Data error, double free or corruption (out): 0x000000000486b460 ***

### ISSUE THREAD

**Issue by CanCanZeng** [openMVG/openMVG#1143]
The problems I have encountered are not the same as those reported by others before，the software provided by openMVG can run correctly, but when I use openMVG as a lib, this problem happened. The program runs well but crashes when it ends.

I tried using the eigen lib from internal, but it doesn't work.

I use gcc4.8.4 on ubuntu14.04.

I just load a SfM_Data and this problem happens.

    SfM_Data sfm_data;
    if(!openMVG::sfm::Load(sfm_data, (reconstruction_dir+"/robust.json"), openMVG::sfm::ALL))
    {
        std::cerr << std::endl
                  << "The input SfM_Data file : " << reconstruction_dir << "/robust.json" << " connot be read." << endl;
        return -1;
    }

**Comment by pmoulon** [comment]
This problem can be due to a conflict between the compilation settings (compiler preprocessor)
You can compiler OpenMVG with this option `-DTARGET_ARCHITECTURE=generic` in order to avoid any usage of compiler intrinsics (sse, avx)

I suppose you are using OpenMVG (master branch). The problem should be fixed in the develop branch.

**Comment by CanCanZeng** [comment]
Thank you for your reply, adding the option -DTARGET_ARCHITECTURE=generic works for me.

I first compile the develop branch without the option, but my problem still happens, after adding the option, my software runs smoothly, thanks a lot.

**Comment by pmoulon** [comment]
Can you please close the issue?
